const $=s=>document.querySelector(s);let fileData=null,tool=null,pdf=null,zoom=1,edits=[];
const status=x=>$("#status").textContent=x;
const pdfjs=await import("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs");
pdfjs.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs";
async function loadFile(f){status("Loading…");fileData=await f.arrayBuffer();pdf=await pdfjs.getDocument({data:fileData.slice(0)}).promise;edits=[];await render();$("#download").disabled=false;status(`Loaded ${pdf.numPages} pages`)}
async function render(){const box=$("#pages");box.innerHTML="";for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),v=p.getViewport({scale:zoom});const d=document.createElement("div");d.className="page";d.style.width=v.width+"px";d.style.height=v.height+"px";const c=document.createElement("canvas");c.width=v.width;c.height=v.height;d.append(c);const o=document.createElement("div");o.className="overlay";d.append(o);box.append(d);await p.render({canvasContext:c.getContext("2d"),viewport:v}).promise;d.onclick=e=>{if(!tool)return;const r=d.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;const el=document.createElement("div");el.className="mark "+tool;el.style.left=x+"px";el.style.top=y+"px";if(tool==="text"||tool==="watermark"){el.textContent=tool==="watermark"?"CONFIDENTIAL":"Editable text";el.contentEditable=true}else{el.style.width="160px";el.style.height="30px"}o.append(el);edits.push({page:i,type:tool,x,y,w:parseFloat(el.style.width)||160,h:parseFloat(el.style.height)||30,text:el.textContent});el.onclick=e=>e.stopPropagation()}}}
$("#open").onclick=()=>$("#file").click();$("#file").onchange=e=>e.target.files[0]&&loadFile(e.target.files[0]);
document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>tool=b.dataset.tool);
$("#zoom").oninput=e=>{zoom=+e.target.value;pdf&&render()};
$("#extract").onclick=async()=>{if(!fileData)return;status("Extracting…");const fd=new FormData();fd.append("file",new Blob([fileData],"application/pdf"),"file.pdf");const r=await fetch("/.netlify/functions/pdf",{method:"POST",body:fd});const j=await r.json();$("#result").textContent=j.text||j.error;status("Ready")};
$("#search").onclick=async()=>{if(!fileData)return;const find=prompt("Find text");if(!find)return;const replace=prompt("Replace with","");const fd=new FormData();fd.append("file",new Blob([fileData],"application/pdf"),"file.pdf");fd.append("find",find);fd.append("replace",replace);const r=await fetch("/.netlify/functions/pdf",{method:"POST",body:fd});if(!r.ok){alert(await r.text());return}fileData=await r.arrayBuffer();pdf=await pdfjs.getDocument({data:fileData.slice(0)}).promise;await render();status("Search & replace complete")};
$("#download").onclick=async()=>{if(!fileData)return;const fd=new FormData();fd.append("file",new Blob([fileData],"application/pdf"),"file.pdf");fd.append("edits",JSON.stringify(edits));const r=await fetch("/.netlify/functions/pdf",{method:"POST",body:fd});const b=await r.blob();const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="AI-PDF-Edited.pdf";a.click()};
$("#ask").onclick=async()=>{if(!fileData)return;const q=$("#prompt").value;const fd=new FormData();fd.append("file",new Blob([fileData],"application/pdf"),"file.pdf");fd.append("prompt",q);const r=await fetch("/.netlify/functions/ai",{method:"POST",body:fd});const j=await r.json();$("#result").textContent=j.text||j.error||"AI is not configured."};
$("#ai").onclick=()=>$("#prompt").focus();
$("#ocr").onclick=()=>alert("OCR requires an OCR provider/API. Add one in the Netlify environment variables and connect it to the function.");
$("#merge").onclick=()=>alert("For multi-file merge, select files in the merge workflow. This Netlify build currently focuses on single-PDF editing/export.");
